name: trackerapp
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^4.9.1
  firebase_auth: ^4.8.0
  firebase_core: ^2.15.1
  fluttertoast: ^8.2.2
  http: ^0.13.6
  shared_preferences: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
  - lib/images/
